### ISSUE TITLE
Contact GDPR expert

### ISSUE THREAD

**Issue by AlesMarconi** [vaimee/my3sec#2]
Preventivo **consulenza** in attesa

Incontro avv. Baldrati follow up - CONSENSO non è considerato base giurica per GDPR al tratamento dei dat ispecialemte per quanto riguarda il rapporto lavorativo che viene regolato dallo statuto dei lavoratori. Bisogna far ricadere l'applicazione sotto la regolamentazione del LEGITTIMO INTERESSE per evitare il consenso. Deve essere basato su Privacy Design. 1) LIA (Legitimate INterests Assesment) legando il software all'aumento della produttività. 2) Produrre documentazione trasparente per estendere le finalità NON al monitoraggio. 3) Verificare algoritmi AI e ML con art. 22 GDPR più nuovo regolamento in vigore dal 2024. Fissato incontro per il 28/12 con parte più tecnica.

**Comment by AlesMarconi** [comment]
contattato per incontro online in materia GDPR - a.latini@sat-web.it
Serve un tecnico all'incontro @lroffia

**Comment by lroffia** [comment]
Quindi questo dovrebbe andare in HOLD?

**Comment by relu91** [comment]
Tomorrow we have a meeting with the relevant person.
